include: '/templates/renovate-dind.gitlab-ci.yml'

variables:
  RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>

stages:
  - test
  - deploy
  - release

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

renovate:dry-run:
  script:
    - renovate --dry-run=full $RENOVATE_EXTRA_FLAGS
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: always

lint:
  image: renovate/node:16.15.0@sha256:4a5086462974dc38d4ff70871ac59429d0acde33eb5b9fb33aa3a9d892b47292
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run prettier
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: always

release:
  image: renovate/node:16.15.0@sha256:4a5086462974dc38d4ff70871ac59429d0acde33eb5b9fb33aa3a9d892b47292
  stage: release
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - git config --global --add safe.directory $PWD
    - npx --no-install semantic-release
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
